### PR TITLE
Updating Bulma from v0.3.0 to v0.5.0

### PR DESCRIPTION
**Pull request by dikaio**
### PLEASE READ THE FOLLOWING INSTRUCTIONS

Thanks for helping out! 😇

* Pull the latest `master` branch
* Run `npm install` to install all Bulma dependencies
* Make sure your Sass code is compliant with the [Bulma Sass styleguide](https://github.com/jgthms/bulma/blob/master/.github/CONTRIBUTING.md#bulma-sass-styleguide)
* If your PR fixes an issue, reference that issue
* If your PR has lots of commits, **rebase** first
* Run `npm run build` and `npm run docs` before submitting your PR

Please remove any unused content (including these instructions) before submitting your issue.

### Pull Request

Fixes #

Changes proposed:

* [ ] Add
* [ ] Fix
* [ ] Remove
* [ ] Update

---
This change is [Reviewable](https://reviewable.io/reviews/cycoresystems/bulma/1)

### CODE REVIEW

**Comment by Ulexus** [comment]
Imports generally have their underscores stripped, but the files are still named with the underscore. 

---

Reviewed 45 of 45 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[scss/elements/_all.scss, line 3 at r1](https://reviewable.io:443/reviews/cycoresystems/bulma/1#-Kw6b11RbrQVwk9y_Fu4:-Kw6b11SN2YR58h6mBO-:btde0sk) ([raw file](https://github.com/cycoresystems/bulma/blob/ed59b4a35e0d84cee504bf88d7f7bc55d4d4e244/scss/elements/_all.scss#L3)):*
> ```SCSS
> @charset "utf-8";
> 
> @import "box";
> ```

Are the underscores not necessary?

---

*[scss/grid/_all.scss, line 3 at r1](https://reviewable.io:443/reviews/cycoresystems/bulma/1#-Kw6auJ0l5Zufj_91pT8:-Kw6auJ0l5Zufj_91pT9:bh9ll2a) ([raw file](https://github.com/cycoresystems/bulma/blob/ed59b4a35e0d84cee504bf88d7f7bc55d4d4e244/scss/grid/_all.scss#L3)):*
> ```SCSS
> @charset "utf-8";
> 
> @import "columns";
> ```

Are these not supposed to retain their underscores?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/bulma/1#-:-Kw6bEA2aM_VVrQ1hbox:b-3b823f)*

**Comment by dikaio** [comment]
Good catch, will update and push here shortly!

**Comment by dikaio** [comment]
*[scss/elements/_all.scss, line 3 at r1](https://reviewable.io:443/reviews/cycoresystems/bulma/1#-Kw6b11RbrQVwk9y_Fu4:-KwC26X2iRt55qVhz8PC:b-gjl9z5) ([raw file](https://github.com/cycoresystems/bulma/blob/ed59b4a35e0d84cee504bf88d7f7bc55d4d4e244/scss/elements/_all.scss#L3)):*
<details><summary><i>Previously, Ulexus (Seán C. McCord) wrote…</i></summary><blockquote>

Are the underscores not necessary?
</blockquote></details>

Turns out underscores have been removed from Bulma all except _all.sass imports. I've updated the current project to be a 1 to 1 sass to SCSS conversion. If you'd prefer we add underscores to keep it more sass like I can make those changes. In my opinion, changing file structure from the original may have unintended consequences down the road.

Pushing 6.0 update now for review.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/bulma/1)*

**Comment by Ulexus** [comment]
Reviewed 241 of 241 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cycoresystems/bulma/1)*

**Pull request merged**
